model: /home/zhang/models/Qwen3.5-0.8B
served_model_name: Qwen3.5-0.8B

trust_remote_code: true
host: "0.0.0.0"
port: 8000

tensor_parallel_size: 1
gpu_memory_utilization: 0.7

max_num_seqs: 8
max_model_len: 16384

enable_auto_tool_choice: true
tool_call_parser: "qwen3_coder"

dtype: "float16"
quantization: "fp8"

reasoning-parser: "qwen3"

